### ISSUE TITLE
response.images.map showing the error: "type of expression is ambiguous without more context"

### ISSUE THREAD

**Issue by analuisamartins** [Swinject/SwinjectMVVMExample#3]
Hi Yoichi, very nice and helpful tutorial, thanks :) I'm trying to follow all the steps in the latest XCode (7.0.1) and I'm stuck in part 4, ImageSearchTableViewModel.swift,  response.images.map is showing
 the error: "type of expression is ambiguous without more context" (image bellow). What I have to do? Can you help? Thanks.

![screen shot 2015-09-29 at 23 54 03](https://cloud.githubusercontent.com/assets/1300887/10180642/d5ba41fc-6706-11e5-8d85-881fde5092a7.png)

**Comment by yoichitgy** [comment]
Hi Ana. I couldn't reproduce the error, but Xcode sometimes has a problem like that when an implicit parameter `$0` is used in nested closures.

Try modifying the `map` like below to explicitly name the parameter?

```
.map { response in
    response.images.map { image in
        ImageSearchTableViewCellModel(image: image) as ImageSearchTableViewCellModeling
    }
}
```

**Comment by yoichitgy** [comment]
I uploaded my repo to exactly follow the blog posts. You can clone the repo and checkout 6554de1d to see my code at [the blog post part 4](https://yoichitgy.github.io/post/dependency-injection-in-mvvm-architecture-with-reactivecocoa-part-4-implementing-the-view-and-viewmodel/) and compare it with yours.

https://github.com/yoichitgy/SwinjectMVVMExample_ForBlog

If you still see the problem, feel free to ask me again here.

**Comment by analuisamartins** [comment]
Thanks for the tip Yoichi.
Actually was my fault :( (new world to me, ios dev)
Yesterday I was trying the tutorial with Himotoki v1.0, I managed to fix ImageEntity adding the new syntax throws / try, but not ResponseEntity, 

with public let images: [ImageEntity], error here: e <|| "hits" 

I changed to: public let images: [String] temporarily to proceed tutorial, later I switched to v0.6 and I forgot this (was causing the error).

Sorry for the trouble, keep up this good work ;)

**Comment by yoichitgy** [comment]
No worries. You gave me a good chance to update the project. Now [Cartfile](https://github.com/Swinject/SwinjectMVVMExample/blob/master/Cartfile) has only tagged version of the frameworks including Himotoki v1.0. I have to update my blogs too ;) Thanks.
