### ISSUE TITLE
'username' field is redundant in Pixabay API

### ISSUE THREAD

**Issue by yoichitgy** [Swinject/SwinjectMVVMExample#6]
It looks Pixabay recently dropped `username` field from [its API](https://pixabay.com/api/docs/), and specifying it gets an error now [as mentioned in a Disqus comment](https://disq.us/url?impression=18c535c0-a81f-11e5-bc4d-002590f3108a&forum=3725555&thread=4093013163&url=https%3A%2F%2Fyoichitgy.github.io%2Fpost%2Fdependency-injection-in-mvvm-architecture-with-reactivecocoa-part-4-implementing-the-view-and-viewmodel%2F%23comment-2420354150%3AqNBIBvX5jM67q9ubxlB4hy8JUSQ&variant=active&experiment=digests&behavior=click&post=2420354150&type=notification.post.moderator&event=email).

Actually it looks the API key contains `username` equivalent parameter now though still an old `username` and API `key` pair is usable.

**Comment by adin283** [comment]
Yes,if request with username parameter,the server will return error 400.
[ERROR 400] Invalid API key. Note: This value is case-sensitive.

**Comment by yoichitgy** [comment]
Thanks @adin283 for the follow up. I fixed the problem.
