### ISSUE TITLE
Xcode 8 and Swift 3 support

### ISSUE THREAD

**Issue by dagio** [Swinject/SwinjectMVVMExample#7]
Is anyone working on Xcode 8 and Swift 3.0 support ?

**Comment by yoichitgy** [comment]
Not yet. I think I can work on Xcode 8 and Swift 3 support in November. It is really appreciated if you are not interested in making a pull request to support them😃

**Comment by yoichitgy** [comment]
With Swinject v2.0.0-beta.2 and Swift 3 version of Alamofire and ReactiveCocoa, Himotoki, Quick and Nimble.
